name: service_one
description: Demo App
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  auto_route: ^6.1.0
  cached_network_image: ^3.2.3
  dio: ^5.1.1
  file: ^6.1.4
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.4
  google_language_fonts: ^2.0.0
  intl: ^0.17.0
  platform_info: ^3.2.0
  responsive_framework: ^1.0.0
  talker_bloc_logger: ^1.1.0
  talker_dio_logger: ^1.3.0
  talker_flutter: ^2.4.3
  velocity_x: ^3.6.0

dev_dependencies:
  auto_route_generator: ^6.1.0
  build_runner: ^2.3.3
  custom_lint: ^0.3.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  riverpod_lint: ^1.2.0


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/